### ISSUE TITLE
range of INDEX functions causes cell compilation error

### ISSUE THREAD

**Issue by kurtdevos** [vallettea/koala#106]
a formula like `SUM(INDEX(D1:F3,1,1):INDEX(D1:F3,1,3))` will trigger 
```
Exception: Failed to compile cell Sheet1!F7 with expression xsum(:index(self.eval_ref('Sheet1!D1:F3', ref = (7, 'F')),1,3)): invalid syntax (<string>, line 1)
Formula: SUM(INDEX(D1:F3,1,1):INDEX(D1:F3,1,3))
```

Excel treats the output of index as a cell, not a value. In this case, the formula is equivalent of `=SUM(D1:F1)`

at least the "basic_evaluation.py" test is affected by this. Any idea's how to fix this ?

**Comment by bleucitron** [comment]
This is due to a stupid `unicode` versus `str` bug.
I fixed it, the PR should be merged soon.
