### ISSUE TITLE
Handle all strings as unicode by default

### ISSUE THREAD

**Issue by bleucitron** [vallettea/koala#108]

**Comment by GliderGeek** [comment]
this is required for python3 support right?

**Comment by danielsjf** [comment]
@brianmay, since Python 3 is supported fully and Python 2 will be depricated in the future, I guess we can close this issue.

**Comment by vallettea** [comment]
yes, @danielsjf do you want to be member of the team ? It doesn't mean you can merge your own PR (a code review from others is still a good thing) but it will enable you to have more rights to close issues etc ?

**Comment by danielsjf** [comment]
@vallettea yes sure!
