### ISSUE TITLE
Get unit tests running & passing

### ISSUE THREAD

**Issue by srp-synengco** [vallettea/koala#123]
It'd be good to get the unit tests up to scratch on this  library

Currently when running `tox` pytest doesn't collect any tests (maybe an import error or something?)

So first things first is to get that going, then work on the tests that fail (maybe disabling some for now that are too far out of date)

Then would be good to add in some test to get a bit more coverage (even if they're pretty basic at first)

Possibly a duplicate of what #41 was for but figured we could use a new ticket

likewise for #35 it'd be good to start a suit of tests for all the functions (no need to do them all, mainly have a working place for them to start with)

Leading on from this we'll try and get some CI going

**Comment by vallettea** [comment]
I agree with you.
We were not very familiar with python testing when we worked on koala.
Travis is very fine. Tell me once you get some tests running so we can set it up.

**Comment by srp-synengco** [comment]
Thanks :) will do
