### ISSUE TITLE
Add support for CONCATENATE / CONCAT

### ISSUE THREAD

**Issue by stonor** [vallettea/koala#135]
Could be great with support for the CONCATENATE function.

**Comment by ranedk** [comment]
+1

**Comment by ranedk** [comment]
I was able to get the concatenate to work. Added the concatenate function to koala/excellib.py
```
def concatenate(*args):
    return "".join(args)
```
Also added "CONCATENATE" to IND_FUN list. I don't know for sure if that's the right way to do it and if I need to check args with some validation.

**Comment by vallettea** [comment]
Thanks for your effort! You should see if tests are passing, add a little test yourself and do a pull request.

**Comment by Brad-eki** [comment]
CONCAT and CONCATENATE are now supported.
