### ISSUE TITLE
not support col:col formate

### ISSUE THREAD

**Issue by 8998663** [vallettea/koala#152]
I have a complicated excel. It  included  col:col formate.
 Program print:
 Pb with ref finance!27:27 Invalid address format 27
Pb with ref finance!442:442 Invalid address format 442
Pb with ref finance!421:421 Invalid address format 421

exception this error:
networkx.exception.NetworkXError: The node NOW is not in the digraph.

How kan I fix it ?

**Comment by vallettea** [comment]
the col:col is not implemented and I personally have no time to do it, so I guess you'll need to put your hands in the code ;)

**Comment by Brad-eki** [comment]
#171 has been merged so looks like col:col is now supported.
