### ISSUE TITLE
User Defined Function (UDF) support

### ISSUE THREAD

**Issue by Brad-eki** [vallettea/koala#169]
Has anyone put thought or effort into having Koala support user defined functions (UDF)?

**Comment by vallettea** [comment]
No

Envoyé de mon iPhone

**Comment by Brad-eki** [comment]
I think I can see a pathway for this.

Recently I have been using Koala in conjunction with a product called xlwings. The combination is extraordinarily powerful in sci/eng data analysis and modelling work.

If you don't know, xlwings is an Excel plugin that manages the COM layer between Excel and Python and has bridged the gap between Pandas+NumPy objects and Excel. There are many other features, like a REST server, Python User Defined Functions (UDF) and the ability to call Visual Basic from Python.

I am thinking that it may well be possible to import xlwings into Koala and utilize its ability to run Visual Basic (I expect VB UDFs) as well as the Python defined UDFs. It would then just be a case of having the Excel function recognition in Koala to be flexible enough to recognize UDFs and choose how to run them "on-the-fly".
