### ISSUE TITLE
What is the use of the associated cells

### ISSUE THREAD

**Issue by danielsjf** [vallettea/koala#179]
I'm trying to debug an issue with row ranges (e.g. Sheet1!5:5). The problem is that some of them get reference cells and others don't. When they get a reference cell, the evaluation function returns only this reference cell which is obviously a very different solution from the range.

Would it be possible to explain what this is used for?

My issue might be related to #40 as it's more likely to run into these issues when a full row/column is selected.

For reference, [these](https://github.com/anthill/koala/blob/029762db49e4f42012f3390ad64a6b53e34225cb/koala/Spreadsheet.py#L603-L606) are the lines I'm referring to.

**Comment by brianmay** [comment]
Unfortunately, my understanding of this particular piece of code is rather weak. As in I have no idea what it does. Still trying to understand what a reference cell is, and why some cells get them and others don't.

**Comment by danielsjf** [comment]
I still have no clue what it does exactly, but it seems that adding the empty cells to the ranges solves this issue.
