### ISSUE TITLE
Function MID is incorrect

### ISSUE THREAD

**Issue by ZloiGremlin** [vallettea/koala#192]
Excel index char start from 1 in python index start is 0
Function of mid range is:
return text[start_num - 1 : start_num + num_chars - 1]

**Comment by brianmay** [comment]
What version are you looking at? There have been some changes in master, so wondering if this problem might has already been fixed?

**Comment by ZloiGremlin** [comment]
I am look to master.
Current version mid is
return text[start_num: start_num + num_chars]
https://github.com/anthill/koala/blob/master/koala/excellib.py#L711

**Comment by brianmay** [comment]
@danielsjf Have you encountered this issue?

**Comment by danielsjf** [comment]
@brianmay, as far as I know, my test excel files aren't using these.

From looking at the test (only one is actually performed), it actually looks like there is an issue (test might be wrong).
https://github.com/anthill/koala/blob/08b053a570bb3f52378464824dd31d281affa6d5/tests/excel/test_functions.py#L458
