### ISSUE TITLE
Deprecate Python 2.7 support

### ISSUE THREAD

**Issue by brianmay** [vallettea/koala#197]
Thinking we should deprecate Python 2.7 support, and maybe remove Python 2.7 in the next major release. In the unlikely event anybody needs Python 2.7 support, please let us know.

@danielsjf what do you think?

**Comment by danielsjf** [comment]
I agree. I keep on hitting 2.7 specific bugs. Solved one Unicode issue, only to stumble upon a numpy issue (which also doesn't do any new 2.7 features anymore) in another pull request.

**Comment by danielsjf** [comment]
How I see it, we should just remove the Python 2.7 version from tox and potentially replace it by 3.7.

We can still allow pull request from people if they would like to create backwards compatibility, but at least we won't do it by default.

**Comment by brianmay** [comment]
Sorry, am falling behind on koala stuff :-(.

I would suggest:

1. Merge & fix all reasonable pull requests that work OK with Python 2.7. Any pull requests fair game (including ones that deprecate stuff), as long as we are reasonably confident there is no breakage.
2. Make a final 0.0.32 release.
3. If there is breakage, and somebody notices, and we think it is worth fixing, we release a 0.0.32+x patch release.
3. Remove tests for Python 2.7, update documentation as required, release as 1.0.0
4. We don't have to actively break Python 2.7, however we don't test it either. Which in
practice probably means it will get broken quickly.

I also note that this project doesn't do some common things:

* There are no trove classifiers in `setup.py` which normally is where Python version compatibility would be mentioned.
* Releases aren't tagged in git.

**Comment by danielsjf** [comment]
Seems good to me. How I read it, in practice this means just the open pull requests plus maybe some small hot fixes.

Or do we already release a non depricated release 0.0.32, then do a 0.0.33 with the deprications and finally a 1.0.0 for the Python 2.7 deprication.

**Comment by brianmay** [comment]
Jef D <notifications@github.com> writes:

> Seems good to me. How I read it, in practice this means just the open
> pull requests plus maybe some small hot fixes.
>
> Or do we already release a non depricated release 0.0.32, then do a
> 0.0.33 with the deprications and finally a 1.0.0 for the Python 2.7
> deprication.

Either way is fine with me. I don't think it matters too much.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by vallettea** [comment]
"Or do we already release a non depricated release 0.0.32, then do a
 0.0.33 with the deprications and finally a 1.0.0 for the Python 2.7
 deprication."

looks good to me

**Comment by danielsjf** [comment]
I guess the current version can be released then. Next week I can look into fixing the open pull requests for the next version.

**Comment by vallettea** [comment]
I pushed to pipy but i add to updgrade to 0.33 because of some trouble with the description
