### ISSUE TITLE
Problem Evaling

### ISSUE THREAD

**Issue by ZloiGremlin** [vallettea/koala#200]
Error in evaluate cell

For example: A1 formula =Sheet2!B1
Sheet2!B1 is empty

g.evaluate('A1') error 
Problem evalling: 'original' for ...

**Comment by ZloiGremlin** [comment]
It is happened after last commits

**Comment by danielsjf** [comment]
When I try to reproduce this, it evaluates to None. Is this not what you would expect?

**Comment by danielsjf** [comment]
This can be reopened if there is a reproducible example and a description of the expected behaviour.
